FYPPROJECT/FINALPROJOCT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mtihani.urls")),
    path('', include("FYPAPP.urls")),
    path('', include("authapp.urls")),
]


from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

FYPPROJECT/FYPAPP/urls.py
from django.urls import path
from . import views
from FYPAPP import views

app_name = 'FYPAPP'

urlpatterns = [
    # path('', views.home.as_view(), name='homepage'),
    path('', views.dashboard, name='dashboard'),


    path('addcourse/', views.add_course, name='add_course'),
    path('display/', views.display, name='display'),

    path('coursedata/', views.course_manage, name='course_manage'),
    path('updatecourse/<str:pk>/', views.update_course, name="update_course"),
    path('deletecourse/<str:pk>/', views.delete_course, name="delete_course"),

    path('addmodule/', views.add_module, name='add_module'),
    path('moduledata/', views.module_manage, name='module_manage'),
    path('updatemodule/<str:pk>/', views.update_module, name="update_module"), 

    path('addquestionchoice/', views.add_question_choice, name="add_question_choice"),
    path('choice/', views.question_choice_manage, name="question_choice_manage"),
    path('short/',views.question_short_manage, name="question_short_manage"),
    # path('updatemodule/', views.update_module, name="update_module"),
   




    path('addquestion/', views.add_question, name="add_question"),
    path('addquestionchoice/', views.add_question_choice, name="add_question_choice"),
    path('addquestionshort/', views.add_question_short, name="add_question_short"),

    path('updatequestion/<str:pk>/', views.update_question, name="update_question"),
    path('updatequestionshort/<str:pk>/', views.update_question_short, name="update_question_short"),
    path('updatequestionchoice/<str:pk>/', views.update_question_choice, name="update_question_choice"),


    path('deletequestion/<str:pk>/', views.delete_question, name="delete_question"),
    path('dataA/', views.question_manage, name="question_manage"),
    path('data/', views.question_short_manage, name="question_short_manage"),
]

FYPPROJECT/mtihani/urls.py
from django.urls import path
from . import views
# from .views import create_exam

app_name = 'mtihani'

urlpatterns = [
    path('addexam/', views.add_exam, name="add_exam"),
    path('exam/', views.exam_manage, name="exam_manage"),
    path('updateexam/<str:pk>/', views.update_exam, name="update_exam"),
    path('selectquestions/', views.select_questions.as_view(), name="select_questions"),
]

FYPPROJECT/FYPAPP/models.py
from django.db import models

# Create your models here.

questionsection = (
    ("YES", "YES"),
    ("NO", " NO"),
    
)
questiontype = (
    ("multichoice Questions", "multichoice Questions"),
    ("short answers Questions", "short answers Questions"),
    ("long answers Questions", "long answers Questions"),
)

questionlevel = (
    ("Normal", "Normal"),
    ("Medium", "Medium"),
    ("Hard", "Hard")
)


class Course(models.Model):
    courseName = models.CharField(max_length=30)
    courseCode = models.CharField(max_length=30)

    def __str__(self):
        return self.courseName

class Masomo(models.Model):
    moduleName = models.CharField(max_length=30)
    moduleCode = models.CharField(max_length=30)
    course = models.ForeignKey('Course', on_delete=models.CASCADE, null=True)
    

    def __str__(self):
        return self.moduleName

class Topic(models.Model):
    topicNumber = models.IntegerField()
    topicName = models.CharField(max_length=30)
    module = models.ForeignKey('Masomo', on_delete=models.CASCADE)
    def __str__(self):
        return self.topicName

class QuestionType(models.Model):
    questiontype = models.CharField(max_length=30)

    def __str__(self):
        return self.questiontype


class QuestionSection(models.Model):
    questionsection = models.CharField(choices=questionsection, null=True, max_length=10)

    def __str__(self):
        return self.questionsection

class QCategory(models.Model):
    questionType = models.CharField(max_length=30, null=True, blank=True, choices=questiontype)
  
    def __str__(self):
        return self.questionType


class Question(models.Model):
    questionType = models.ForeignKey(QCategory, on_delete=models.CASCADE, default='multichoice_Questions')
    questionLevel = models. CharField(max_length=30, null=True, choices=questionlevel)
    somo = models.ForeignKey('Masomo', on_delete=models.CASCADE)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    questionText = models.TextField ()
    

    def __str__(self): 
        return self.questionText

class QuestionChoice(models.Model):
    question = models.TextField(max_length=100)
    somo = models.ForeignKey('Masomo', on_delete=models.CASCADE, null=True, blank=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, null=True, blank=True)
    option1 = models.TextField(max_length=100)
    option2 = models.TextField(max_length=100)
    option3 = models.TextField(max_length=100)
    option4 = models.TextField(max_length=100)
    answer = models.TextField(max_length=50)

    def __str__(self):
        return self.question

class QuestionShortterm(models.Model):
    somo = models.ForeignKey('Masomo', on_delete=models.CASCADE, null=True, blank=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, null=True, blank=True)
    question = models.TextField(max_length=100)
    answer = models.TextField(max_length=100)


class QuestionLongTerm(models.Model):
    somo = models.ForeignKey('Masomo', on_delete=models.CASCADE,null=True, blank=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, null=True, blank=True)
    question = models.TextField ()
    answer = models.TextField (max_length=100)

FYPPROJECT/FYPAPP/forms.py
from django import forms
from .models import Masomo, Question, Course, QCategory,QuestionChoice, QuestionShortterm


class MasomoForm(forms.ModelForm):
    class Meta:
        model = Masomo
        fields = '__all__'

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class QCategoryForm(forms.ModelForm):
    class Meta:
        model = QCategory
        fields = '__all__'      

class QuestionChoiceForm(forms.ModelForm):
    class Meta:
        model = QuestionChoice
        fields = '__all__'
 
class QuestionShorttermForm(forms.ModelForm):
    class Meta:
        model = QuestionShortterm   
        fields = '__all__'   

        
           
# class QuestionForm(models.Model):
#     questiontype = models.ForeignKey('QuestionType', on_delete=models.CASCADE)
#     questionLevel = models. ForeignKey('QuestionLevel', on_delete=models.CASCADE)
#     somo = models.ForeignKey('Masomo', on_delete=models.CASCADE)
#     topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
#     questionText = models.TextField ()
    

FYPPROJECT/FYPAPP/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from .models import Course, Masomo, Question,QuestionChoice,QuestionShortterm
from .forms import QuestionForm, CourseForm, MasomoForm, QuestionChoiceForm, QuestionShorttermForm
from django.db import connection
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def dashboard(request):
    return render(request, 'FYPAPP/dashboard.html')
    # return render(request,'teacher/teacher_dashboard.html'

# def dashboard(request):
#     return render(request, 'FYPAPP/dashboard.html')

# @login_required
def course_manage(request):
    context = {'course':  Course.objects.all()}
    return render(request, 'FYPAPP/course_manage.html', context)
    
def total(request):
    courses = Masomo.objects.all()
    totalcourse = courses.count()
    print(totalcourse)
    context = {'courses':courses, 'totalcourse':totalcourse}
    return render(request, 'FYPAPP/course_manage.html', context)

def add_course(request):
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/coursedata')   

    else:
        form = CourseForm()
        return render(request, 'FYPAPP/add_course.html', {"form":form})    
         
def update_course(request, pk):
    course = Course.objects.get(id=pk)
    form = CourseForm(instance=course)

    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('/coursedata')

    context = {"form":form}
    return render(request, 'FYPAPP/add_course.html', context)

def delete_course(request, pk):
    course = Course.objects.get(id=pk)
    course.delete()
    return redirect('/coursedata')
# *******************************************************************

def module_manage(request):
    context = {'module_manage': Masomo.objects.all()}
    return render(request, 'FYPAPP/module_manage.html', context)


def add_module(request):
    if request.method == "POST":
        form = MasomoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/moduledata')

    else:
         form = MasomoForm()
         return render(request, 'FYPAPP/add_module.html', {"form":form})           



def update_module(request, pk):
    masomo = Masomo.objects.get(id=pk)
    form = MasomoForm(instance=masomo)

    if request.method == "POST":
        form = MasomoForm(request.POST, instance=masomo)
        if form.is_valid():
            form.save()
            return redirect('/moduledata')

    context = {"form":form}
    return render(request, 'FYPAPP/add_module.html', context)  

# ********************************************************************************* 

# ****************************************************************************


def question_manage(request):
    context = {'question_manage': Question.objects.all()}
    return render(request, "FYPAPP/question_manage.html", context)

def question_choice_manage(request):
    context = {'question_choice': QuestionChoice.objects.all()}
    return render(request, "FYPAPP/question_choice_manage.html", context)

def question_short_manage(request):
    context = {'question_manage': QuestionShortterm.objects.all()}
    return render(request, "FYPAPP/question_manage.html", context)

# ***************************ADD QUESTIONS HAPA ***************************************
def add_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            
        return redirect('/data')  

    else:
            form = QuestionForm()
            return render(request, "FYPAPP/add_question.html", {"form":form})         

def add_question_choice(request):
    if request.method == "POST":
        form = QuestionChoiceForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/choice')
    else:
        form = QuestionChoiceForm()
        return render(request, "FYPAPP/add_question_choice.html", {'form':form})    
        
         

def add_question_short(request):
    if request.method == "POST":
        form= QuestionShorttermForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect('/data')

    else:
        form = QuestionShorttermForm()
        return render(request, "FYPAPP/add_question.html", {"form":form})        
# *****************************UPDATE QUESTION******************************************************************

def update_question(request, pk):
    question = Question.objects.get(id=pk)
    form = QuestionForm(instance=question)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect("/data")

    context = {"form": form }
    return render(request, 'FYPAPP/add_question.html', context)

def update_question_short(request,pk):
    question = QuestionShortterm.objects.get(id=pk)
    form = QuestionShorttermForm(instance=question)

    if request.method == "POST":
        form = QuestionShorttermForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
        return redirect('/short')    

    context = {'form':form}
    return render(request, 'FYPAPP/add_question.html', context)            

def update_question_choice(request, pk):
    question = QuestionChoice.objects.get(id=pk)
    form = QuestionChoiceForm(instance=question)

    if request.method == "POST":
        form = QuestionChoiceForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
        return redirect('/choice')

    context = {'form':form}
    return render(request, 'FYPAPP/add_question_choice.html', context)


#***************************************************************** 
        
def delete_question(request, pk):
    question = Question.objects.get(id=pk)
    if request.method == "POST":
        question.delete()
    return redirect("/data")


    context = {"question":question}
    return render(request, 'FYPAPP/question_manage.html', context)
#   ****************************************************************



      






def display(request):
    category = QuestionChoice.objects.filter(category_id=1).only('question')
    print(category)
    print(connection.queries)
    return render(request, "FYPAPP/add_question_choice.html", {'category':category})        



# class home(TemplateView):
#     template_name = 'FYPAPP/home.html'


# class dashboard(TemplateView):
#     template_name = 'FYPAPP/dashboard.html'
  

FYPPROJECT/templates/FYPAPP/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Examination Machine</title>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    
    <style>

        
        body {
            background-color: #e6e6e6; 
        }
        .boxkushoto .sidebar{
            background: rgba(25,107,140,255);
            position: fixed;
            top: 0;
            left: 0;
            width: 240px;
            height: 100vh;
            overflow-y: auto;
            overflow-x: hidden;
            transition: all 0.3s ease;
        }

        /* .navigationBar {
            background-color: white;
            height: 50px;
            display: flex;
            padding: 38px 0px;
            align-items: center;
            box-shadow: 0 4px 2px -2px #c5c6c7;
        } */

        .sidebar-header {
            padding: 10px 25px 10px 15px;
        }
        .sidebar-logo-container {
            background-color: rgb(0, 0, 0, 0.2);
            border-radius: 8px;
            padding-left: 3px;
            display: flex;
        }

        .brand-name-container {
            margin: 10px 55px 0px 2px;
            padding: 0px;
        }

        .brand-name {
            color: white;
            margin: 0px;
            line-height: 1.1rem; 
            font-size: 16px;
            letter-spacing: 1px;
            font-family: 'Roboto', sans-serif;
        }
        .brand-subname {
            font-weight: 300;
            font-size: 14px;
        }
        .navigation-list {
            list-style-type:none;
            padding: 0px 18px;
            margin-top: 30px;
        }
        .btn{
            color: white;
        }
        .exam-header{
            color: black;
        }
        
    </style>
    </head>

    <body>
   
    <div class="boxkushoto">
        <div class="sidebar">
            <div class="sidebar-header">
                <div class="sidebar-logo-container">
                    <div class="brand-name-container">
                        <p class="brand-name">
                            Examination<br />
                            <span class="brand-subname">
                                Machine
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="sidebar-body">
                <ul class="navigation-list">
                    <div class="exam-header"><h5>Exam</h5></div>
                    <hr style="color:rgb(255, 255, 255);margin-top:12px;">

                    <div>
                        
                        <button type="button" class="btn btn-white">DASHBOARD</button>
                    </div>
                    <br/>

                    <div class="dropdown">
                        <button class="btn btn-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          COURSE
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:add_course' %}">ADD COURSE</a></li>
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:course_manage' %}">MANAGE COURSE</a></li>
                          
                        </ul>
                    </div>
                    <br/>

                    <div class="dropdown">
                        <button class="btn btn-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          MODULE
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:add_module' %}">ADD MODULE</a></li>
                          <li><a class="dropdown-item" href="#">ADD MODULE TOPICS</a></li>
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:module_manage' %}">MANAGE MODULE</a></li>
                        </ul>
                    </div>
                    <br/>

                    <div class="dropdown">
                        <button class="btn"  id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          QUESTION
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:add_question' %}">ADD MULTIPE CHOICE</a></li>
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:add_question' %}">ADD SHORT TERMS</a></li>
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:add_question' %}">ADD LONG TERMS</a></li>
                          <li><a class="dropdown-item" href="{% url 'FYPAPP:question_manage' %}">MANAGE QUESTION</a></li>
                        </ul>
                    </div>
                    <br/>

                    <div class="dropdown">
                        <!-- <i class="fas fa-users"></i> -->
                        <button class="btn btn-white" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false" >QUESTION PAPER </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item" href="{% url 'mtihani:add_exam' %}">ADD EXAM</a></li>
                            <li><a class="dropdown-item" href="{% url 'mtihani:exam_manage' %}"> MANAGE EXAM </a></li>
                        </ul>
                        <!-- <a href="{% url 'FYPAPP:question_manage' %}" class="btn btn-outline-dark ms-2">List All</a> -->

                    </div>
                    <br/>

                    <hr style="color:rgb(255, 255, 255);margin-top:30px;">
                    <div class="exam-header"><h5>Profile</h5></div>
                    <hr style="color:rgb(255, 255, 255);margin-top:30px;">
                    <div>
                        <i class="fas fa-users"></i>
                        <button type="button" class="btn btn-white">PROFILE</button>
                    </div>

                </ul>

            </div>
        </div>
        
        <!-- <div class="content">
            <div class="navigationBar">
                <button id="sidebarToggle" class="btn sidebarToggle">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div> -->
        
    </div>
 
    <!-- <h3 class="text-center">LOGIN</h3> -->
    <script>
        let sidebarToggle = document.querySelector(".sidebarToggle");
        sidebarToggle.addEventListener("click", function(){
            document.querySelector("body").classList.toggle("active");
            document.getElementById("sidebarToggle").classList.toggle("active");
        })
    </script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    {% block content %}
    {% endblock content%}
  </body>


</html>

FYPPROJECT/templates/FYPAPP/question_manage.html
{% extends 'FYPAPP/home.html' %}

{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #566787;
	background: #f5f5f5;
	font-family: 'Varela Round', sans-serif;
	font-size: 13px;
}
.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {        
	padding-bottom: 15px;
	background: #435d7d;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 90px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 79px;
}
table.table tr th:last-child {
	width: 10px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}	
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.pagination {
	float: right;
	margin: 0 0 5px;
}
.pagination li a {
	border: none;
	font-size: 13px;
	min-width: 30px;
	min-height: 30px;
	color: #999;
	margin: 0 2px;
	line-height: 30px;
	border-radius: 2px !important;
	text-align: center;
	padding: 0 6px;
}
.pagination li a:hover {
	color: #666;
}	
.pagination li.active a, .pagination li.active a.page-link {
	background: #03A9F4;
}
.pagination li.active a:hover {        
	background: #0397d6;
}
.pagination li.disabled i {
	color: #ccc;
}
.pagination li i {
	font-size: 16px;
	padding-top: 6px
}
.hint-text {
	float: left;
	margin-top: 10px;
	font-size: 13px;
}    
/* Custom checkbox */
.custom-checkbox {
	position: relative;
}
.custom-checkbox input[type="checkbox"] {    
	opacity: 0;
	position: absolute;
	margin: 5px 0 0 3px;
	z-index: 9;
}
.custom-checkbox label:before{
	width: 18px;
	height: 18px;
}
.custom-checkbox label:before {
	content: '';
	margin-right: 10px;
	display: inline-block;
	vertical-align: text-top;
	background: white;
	border: 1px solid #bbb;
	border-radius: 2px;
	box-sizing: border-box;
	z-index: 2;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	content: '';
	position: absolute;
	left: 6px;
	top: 3px;
	width: 6px;
	height: 11px;
	border: solid #000;
	border-width: 0 3px 3px 0;
	transform: inherit;
	z-index: 3;
	transform: rotateZ(45deg);
}
.custom-checkbox input[type="checkbox"]:checked + label:before {
	border-color: #03A9F4;
	background: #03A9F4;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	border-color: #fff;
}
.custom-checkbox input[type="checkbox"]:disabled + label:before {
	color: #b8b8b8;
	cursor: auto;
	box-shadow: none;
	background: #ddd;
}
/* Modal styles */
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}	
.modal form label {
	font-weight: normal;
}	
</style>
<script>
$(document).ready(function(){
	// Activate tooltip
	$('[data-toggle="tooltip"]').tooltip();
	
	// Select/Deselect checkboxes
	var checkbox = $('table tbody input[type="checkbox"]');
	$("#selectAll").click(function(){
		if(this.checked){
			checkbox.each(function(){
				this.checked = true;                        
			});
		} else{
			checkbox.each(function(){
				this.checked = false;                        
			});
		} 
	});
	checkbox.click(function(){
		if(!this.checked){
			$("#selectAll").prop("checked", false);
		}
	});
});
</script>
</head>
<body>
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2>Manage <b>Question</b></h2>
					</div>
			
				</div>
			</div>
			<table class="table table-striped table-hover">
                
                    <thead>
                        <tr>
                            
                            <th>Question</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    {% for question in question_manage %}
                    <tr>
                        <td>{{question.question}}</td>
                        <!-- <td>{{question.topic}}</td> -->
                        <!-- <td>{{data.questionType}}</td> -->
                        <!-- <td>{{question.questionType}}</td> -->
                        <td>
							<div class="container-fluid">
								<div class="row">
									<div class="col-6">
										<a href="{% url 'FYPAPP:update_question_short' question.id %}" class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</a>

										<!-- <a href="{% url 'FYPAPP:add_question' %}" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a> -->
										<!-- <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a> -->
									</div>
	

									<div class="col-6">
										<a href="{% url 'FYPAPP:update_question' question.id %}" class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</a>

										<!-- <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a> -->
										<!-- <a href="{% url 'FYPAPP:delete_question' question.id %}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a> -->
									</div>
								</div>
							</div>
						</td>
                    </tr>
                    {% endfor %}
                
			</table>
		
		</div>
	</div>        
</div>


</body>
</html>

{% endblock content%} 