FYPPROJECT/FINALPROJOCT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mtihani.urls")),
    path('', include("FYPAPP.urls")),
    path('', include("authapp.urls")),
]


from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

FYPPROJECT/FYPAPP/urls.py
from django.urls import path
from . import views
from FYPAPP import views

app_name = 'FYPAPP'

urlpatterns = [
    # path('', views.home.as_view(), name='homepage'),
    path('', views.dashboard, name='dashboard'),


    path('addcourse/', views.add_course, name='add_course'),
    path('display/', views.display, name='display'),

    path('coursedata/', views.course_manage, name='course_manage'),
    path('updatecourse/<str:pk>/', views.update_course, name="update_course"),
    path('deletecourse/<str:pk>/', views.delete_course, name="delete_course"),

    path('addmodule/', views.add_module, name='add_module'),
    path('moduledata/', views.module_manage, name='module_manage'),
    path('updatemodule/<str:pk>/', views.update_module, name="update_module"), 

    path('addquestionchoice/', views.add_question_choice, name="add_question_choice"),
    path('choice/', views.question_choice_manage, name="question_choice_manage"),
    path('short/',views.question_short_manage, name="question_short_manage"),
    # path('updatemodule/', views.update_module, name="update_module"),
   




    path('addquestion/', views.add_question, name="add_question"),
    path('addquestionchoice/', views.add_question_choice, name="add_question_choice"),
    path('addquestionshort/', views.add_question_short, name="add_question_short"),

    path('updatequestion/<str:pk>/', views.update_question, name="update_question"),
    path('updatequestionshort/<str:pk>/', views.update_question_short, name="update_question_short"),
    path('updatequestionchoice/<str:pk>/', views.update_question_choice, name="update_question_choice"),


    path('deletequestion/<str:pk>/', views.delete_question, name="delete_question"),
    path('dataA/', views.question_manage, name="question_manage"),
    path('data/', views.question_short_manage, name="question_short_manage"),
]

FYPPROJECT/mtihani/urls.py
from django.urls import path
from . import views
# from .views import create_exam

app_name = 'mtihani'

urlpatterns = [
    path('addexam/', views.add_exam, name="add_exam"),
    path('exam/', views.exam_manage, name="exam_manage"),
    path('updateexam/<str:pk>/', views.update_exam, name="update_exam"),
    path('selectquestions/', views.select_questions.as_view(), name="select_questions"),
]

FYPPROJECT/mtihani/models.py
from django.db import models
from FYPAPP.models import Masomo, Course, QuestionSection, QCategory, QuestionChoice, QuestionShortterm,QuestionLongTerm
import datetime
# Create your models here.
class Exam(models.Model):
    examinationType = models.CharField(max_length=30,  null=True, blank=True)
    examinationName = models.CharField(max_length=30,  null=True, blank=True)
    semeter = models.IntegerField( null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE,  null=True, blank=True)
    module = models.ForeignKey(Masomo, on_delete=models.CASCADE,  null=True, blank=True)
    questionChoice = models.ForeignKey(QuestionChoice, on_delete=models.CASCADE, null=True, blank=True)
    questionChoice = models.ForeignKey(QuestionShortterm, on_delete=models.CASCADE, null=True, blank=True)
    questionLong = models.ForeignKey(QuestionLongTerm, on_delete=models.CASCADE, null=True, blank=True)
    # choice = models.ForeignKey(QuestionAinazote, on_delete=models.CASCADE, null=True, blank=True)
    examDuration = models.TimeField( null=True, blank=True)
    examFullmark = models.IntegerField ( null=True, blank=True)
    questionSection = models.ForeignKey(QuestionSection, on_delete=models.CASCADE,  null=True, blank=True)
    examinationDescription = models.TextField( null=True, blank=True)

    # def __str__(self):
    #     return self.examDuration

class SavedExam(models.Model):
    mtihani = models.TextField(null=True, blank=True)



class Mtihani(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE,  null=True, blank=True)
    module = models.ForeignKey(Masomo, on_delete=models.CASCADE,  null=True, blank=True)
    modulecode = models.CharField(max_length=50, null=True, blank=True)
    semeter = models.CharField(max_length=50, null=True, blank=True)
    exam_name = models.CharField(max_length=50)
    examdate = models.DateField(null=True)
    examtime = models.CharField(max_length=50, null=True, blank=True)
    examinationDescription = models.CharField(max_length=300, null=True, blank=True)
    examinationDescription2 = models.CharField(max_length=300, null=True, blank=True)
    examinationDescription3 = models.CharField(max_length=300, null=True, blank=True)
    num_questions = models.IntegerField()
    num_shortquestions = models.IntegerField()
    num_longquestions = models.IntegerField()

FYPPROJECT/mtihani/forms.py
from django import forms
from .models import Exam,Mtihani

class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = '__all__'



class MtihaniForm(forms.ModelForm):
    # examdate = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = Mtihani
        fields = '__all__'        

FYPPROJECT/mtihani/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Exam, Mtihani
from .forms import ExamForm,MtihaniForm
from FYPAPP.models import QCategory, QuestionChoice, QuestionShortterm, QuestionLongTerm, Course
from FYPAPP.forms import QCategoryForm, QuestionChoiceForm
from django.db import connection
import random
from .pdf import html_to_pdf 
from django.views.generic import View
from django.http import HttpResponse
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from django.template.loader import render_to_string
from weasyprint import HTML


def exam_manage(request):
    context = {'exam_manage': Mtihani.objects.all()}
    # context2 = {'question_choice': QuestionChoice.objects.all()}
    return render(request, "mtihani/exam_manage.html", context)



def add_exam(request):
    if request.method == "POST":
        form = ExamForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/exam')  
    else:
            form = ExamForm()
            return render(request, "mtihani/add_exam.html", {"form":form})   

      


def update_exam(request, pk):
    mtihani = Exam.objects.get(id=pk)
    form = ExamForm(instance=mtihani)

    if request.method == "POST":
        form = ExamForm(request.POST, instance=mtihani)  
        if form.is_valid():
            form.save()  
            return redirect('/exam')  

    context = {"form":form}
    return render(request, 'mtihani/add_exam.html', context)                  

# class select_questions(View):
#     def get(self, request, *args, **kwargs):
#         return render(request, 'mtihani/generate_exam.html')
    
#     def post(self, request, *args, **kwargs):
#         # Retrieve num_questions, num_shortquestions, and num_longquestions values from POST request
#         num_questions = int(request.POST.get('num_questions'))
#         num_shortquestions = int(request.POST.get('num_shortquestions'))
#         num_longquestions = int(request.POST.get('num_longquestions'))
        
#         # Retrieve questions from database and shuffle them
#         questions = list(QuestionChoice.objects.all())
#         random.shuffle(questions)
        
#         questionshort = list(QuestionShortterm.objects.all())
#         random.shuffle(questionshort)
        
#         questionlong = list(QuestionLongTerm.objects.all())
#         random.shuffle(questionlong)
        
#         # Save only the required number of questions
#         questions = questions[:num_questions]
#         for question in questions:
#             question.save()
        
#         questionshort = questionshort[:num_shortquestions]
#         for question in questionshort:
#             question.save()
        
#         questionlong = questionlong[:num_longquestions]
#         for question in questionlong:
#             question.save()
        
#         # Create a context containing the questions
#         context = {
#             'num_questions': num_questions,
#             'num_shortquestions': num_shortquestions,
#             'num_longquestions': num_longquestions,
#             'questions': questions,
#             'questionshort': questionshort,
#             'questionlong': questionlong,
#         }
        
#         # Render the HTML template with the context
#         html = render_to_string('pdf2.html', {'questions': questions, 'questionshort': questionshort, 'questionlong': questionlong})
#         response = HttpResponse(content_type='application/pdf')
#         response['Content-Disposition'] = 'filename="questions.pdf"'
#         buffer = BytesIO()
#         HTML(string=html).write_pdf(buffer)
#         response.write(buffer.getvalue())

#         # Return the PDF as an HTTP response
#         return response



class select_questions(View):
    def get(self, request, *args, **kwargs):
        form = MtihaniForm()
        return render(request, 'mtihani/generate_exam.html', {'form':form})
    
    def post(self, request, *args, **kwargs):
        form = MtihaniForm(request.POST)
        if form.is_valid():
            course = form.cleaned_data['course']
            semeter = form.cleaned_data['semeter']
            module = form.cleaned_data['module']
            modulecode = form.cleaned_data['modulecode']
            exam_name = form.cleaned_data['exam_name']
            examtime = form.cleaned_data['examtime']
            examdate = form.cleaned_data['examdate']
            examinationDescription = form.cleaned_data['examinationDescription']
            examinationDescription2 = form.cleaned_data['examinationDescription2']
            examinationDescription3 = form.cleaned_data['examinationDescription3']
            num_questions = form.cleaned_data['num_questions']
            num_shortquestions = form.cleaned_data['num_shortquestions']
            num_longquestions = form.cleaned_data['num_longquestions']

            
        
        # Retrieve questions from database and shuffle them
            questions = list(QuestionChoice.objects.all())
            random.shuffle(questions)

            questionshort = list(QuestionShortterm.objects.all())
            random.shuffle(questionshort)

            questionlong = list(QuestionLongTerm.objects.all())
            random.shuffle(questionlong)

            # Save only the required number of questions
            questions = questions[:num_questions]
            for question in questions:
                question.save()

            questionshort = questionshort[:num_shortquestions]
            for question in questionshort:
                question.save()

            questionlong = questionlong[:num_longquestions]
            for question in questionlong:
                question.save()

            # Create a context containing the questions, semester, and exam_name
            context = {
                'course': course,
                'semeter': semeter,
                'module': module,
                'modulecode' : modulecode,
                'exam_name': exam_name,
                'examdate': examdate,
                'examtime': examtime,
                'examinationDescription':examinationDescription,
                'examinationDescription2':examinationDescription2,
                'examinationDescription3':examinationDescription3,
                'num_questions': num_questions,
                'num_shortquestions': num_shortquestions,
                'num_longquestions': num_longquestions,
                'questions': questions,
                'questionshort': questionshort,
                'questionlong': questionlong,
            }

            # Render the HTML template with the context
            html = render_to_string('pdf2.html', context)
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = 'filename="questions.pdf"'
            buffer = BytesIO()
            HTML(string=html).write_pdf(buffer)
            response.write(buffer.getvalue())

            # Return the PDF as an HTTP response
            return response
        
        return render(request, 'mtihani/generate_exam.html', {'form': form})
   
    

FYPPROJECT/templates/mtihani/collection.html
{% extends 'mtihani/home.html' %}

{% block content%}
<div class="container card p-3 boarder-dark" style="width: 95%;">
    <h5 class="text-center">ADD EXAM</h5>
    <hr>
    <form method="POST" action="#">
        {csrf_token}
        <div class="row g-1">
            <div class="col">
                <div class="form-outline">
                    <label class="form-label">ExaminationType</label>
                    {{ form.examinationType  }}
                </div>
            </div>
        </div>

        <div class="row g-1">
            <div class="col">
                <div class="form-outline">
                    <label class="form-label">ExaminationName</label>
                    {{ form.examinationName }}
                </div>
            </div>
        </div>
    </form>
</div>




{% endblock content%}

FYPPROJECT/templates/mtihani/exam_manage.html
{% extends 'mtihani/home.html' %}

{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #566787;
	background: #f5f5f5;
	font-family: 'Varela Round', sans-serif;
	font-size: 13px;
}
.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {        
	padding-bottom: 15px;
	background: #435d7d;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 90px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 79px;
}
table.table tr th:last-child {
	width: 10px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}	
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.pagination {
	float: right;
	margin: 0 0 5px;
}
.pagination li a {
	border: none;
	font-size: 13px;
	min-width: 30px;
	min-height: 30px;
	color: #999;
	margin: 0 2px;
	line-height: 30px;
	border-radius: 2px !important;
	text-align: center;
	padding: 0 6px;
}
.pagination li a:hover {
	color: #666;
}	
.pagination li.active a, .pagination li.active a.page-link {
	background: #03A9F4;
}
.pagination li.active a:hover {        
	background: #0397d6;
}
.pagination li.disabled i {
	color: #ccc;
}
.pagination li i {
	font-size: 16px;
	padding-top: 6px
}
.hint-text {
	float: left;
	margin-top: 10px;
	font-size: 13px;
}    
/* Custom checkbox */
.custom-checkbox {
	position: relative;
}
.custom-checkbox input[type="checkbox"] {    
	opacity: 0;
	position: absolute;
	margin: 5px 0 0 3px;
	z-index: 9;
}
.custom-checkbox label:before{
	width: 18px;
	height: 18px;
}
.custom-checkbox label:before {
	content: '';
	margin-right: 10px;
	display: inline-block;
	vertical-align: text-top;
	background: white;
	border: 1px solid #bbb;
	border-radius: 2px;
	box-sizing: border-box;
	z-index: 2;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	content: '';
	position: absolute;
	left: 6px;
	top: 3px;
	width: 6px;
	height: 11px;
	border: solid #000;
	border-width: 0 3px 3px 0;
	transform: inherit;
	z-index: 3;
	transform: rotateZ(45deg);
}
.custom-checkbox input[type="checkbox"]:checked + label:before {
	border-color: #03A9F4;
	background: #03A9F4;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	border-color: #fff;
}
.custom-checkbox input[type="checkbox"]:disabled + label:before {
	color: #b8b8b8;
	cursor: auto;
	box-shadow: none;
	background: #ddd;
}
/* Modal styles */
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}	
.modal form label {
	font-weight: normal;
}	
</style>
<script>
$(document).ready(function(){
	// Activate tooltip
	$('[data-toggle="tooltip"]').tooltip();
	
	// Select/Deselect checkboxes
	var checkbox = $('table tbody input[type="checkbox"]');
	$("#selectAll").click(function(){
		if(this.checked){
			checkbox.each(function(){
				this.checked = true;                        
			});
		} else{
			checkbox.each(function(){
				this.checked = false;                        
			});
		} 
	});
	checkbox.click(function(){
		if(!this.checked){
			$("#selectAll").prop("checked", false);
		}
	});
});
</script>
</head>
<body>
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2>Manage <b>Exam</b></h2>
					</div>
					<div class="col-sm-6">
						<a href="#addCourseModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Module</span></a>
						<a href="#deleteCourseModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>						
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
                
                    <thead>
                        <tr>
                            <!-- <th>examinationType</th> -->
                            <th>course</th>
                            <th>semeter</th> 
							<!-- <th>Generate Exam</th> -->
                           
                        </tr>
                    </thead>
                    {% for exam in exam_manage %}
                    <tr>
                       
                        <td>{{ exam.course }}</td>
                        <td>{{ exam.semeter }}</td>
						<td>
							<!-- <button class="btn btn-primary">Generate Exam</button> -->
							<a href="{% url 'mtihani:select_questions' %}" class="btn btn-primary">Generate Exam</a>
						</td>
						<!-- <td>{{ exam.module }}</td>  -->
                    	<td>
							<div class="container-fluid">
								<div class="row">
									<div class="col-6">
										<a href="{% url 'mtihani:update_exam' exam.id %}" class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</a>
									</div>
	
									<div class="col-6">
										<!-- <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a> -->
										<a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
									</div>
									
								</div>
							</div>
						</td>
                          
						
                    </tr>
                    {% endfor %}
			
			</table>
		
		</div>
	</div>        
</div>


</body>
</html>

{% endblock content%} 

FYPPROJECT/templates/mtihani/mtihani.html
{% extends 'mtihani/home.html' %}

{% block content %}


			<form method="POST" action="#">
                {% csrf_token %}
                
                  
             		  <div class="row g-5">
                  
                    
					<div class="col">
						<label for="num_questions">Number of questions:</label>
  						<input type="number" name="num_questions" id="num_questions">
  						<!-- <button type="submit">Select</button> -->

					</div>
				
					<div class="col">
						<label for="num_shortquestions">Number of questionsshort:</label>
  						<input type="number" name="num_shortquestions" id="num_shortquestions">
  						<!-- <button type="submit">Select</button> -->

					</div>

					<div class="col">
						<label for="num_longquestions">Number of questionlong:</label>
						<input type="number" name="num_longquestions" id="num_longquestions">
						
					</div>
					
                  </div>
                  <hr>
                     
                  <div class="mt-5">
					<button type="submit" class="btn btn-primary">Submit</button>
					<button type="reset" class="btn btn-secondary ms-2">Reset</button>
					<a href="{% url 'mtihani:GeneratePdf' %}" class="btn btn-primary">Print Examination</a>
					
				</div>
            </form>
		
		</div>
	</div>        
</div>


</body>
</html>

{% endblock content%} 

FYPPROJECT/templates/mtihani/saved_exams.html
{% block content %}
    <h1>Saved Exams</h1>
    <ul>
    {% for exam in exams %}
        <li>Exam {{ exam.id }}: {{ exam.timestamp }}</li>
    {% empty %}
        <li>No saved exams</li>
    {% endfor %}
    </ul>
{% endblock %}